import pizzaImage from "./foods/Pizza-Dough_1.jpg";
import PhillyCheesesteakImage from "./foods/Philly-Cheesesteak-2.jpg";
import GourmetBurgImage from "./foods/loaded-burgers-featured-3.jpg";
import CeasarSalImage from "./foods/grilled-caesar-chicken-salad-6.jpg";
import wingsImage from "./foods/delish-fried-chicken-wings-5.jpg";
import chzfriesImage from "./foods/cheese-fries-4.jpg";
export const sample_foods = [
  {
    id: 1,
    name: "Pizza",
    cookTime: "30 mins",
    price: 10,
    favorite: false,
    origin: ["New York"],
    stars: 5,
    imageUrl: pizzaImage,
    tags: ["pizza", "italian", "cheese", "pepperoni", "tomato", "dough"],
  },
  {
    id: 2,
    name: "Philly Cheesesteak",
    cookTime: "20 mins",
    price: 15,
    favorite: true,
    origin: ["Philadelphia", "Persia", "Italy", "Greece", "China"],
    stars: 5,
    imageUrl: PhillyCheesesteakImage,
    tags: ["SlowFood", "Lunch", "apetizers"],
  },
  {
    id: 3,
    name: "Gourmet Hamburger",
    cookTime: "18 mins",
    price: 22,
    favorite: false,
    origin: ["Germany", "USA"],
    stars: 4,
    imageUrl: GourmetBurgImage,
    tags: ["SlowFood", "Hamburger", "Lunch", "Dinner", "Beef"],
  },
  {
    id: 4,
    name: "Loaded French Fries",
    cookTime: "10 mins",
    price: 8,
    favorite: true,
    origin: ["Belgium", "France", "USA"],
    stars: 5,
    imageUrl: chzfriesImage,
    tags: [
      "FastFood",
      "Fry",
      "Lunch",
      "Dinner",
      "Potato",
      "Cheese",
      "Bacon",
      "Sour Cream",
      "Chives",
      "Jalapeno",
      "apetizers",
    ],
  },
  {
    id: "5",
    name: "Dozen Delish Chicken Wings",
    cookTime: "12 mins",
    price: 14,
    favorite: false,
    origin: ["USA", "Africa"],
    stars: 5,
    imageUrl: wingsImage,
    tags: [
      "apetizers",
      "Fry",
      "Chicken",
      "Lunch",
      "Dinner",
      "FastFood",
      "Wings",
      "Hot",
      "Spicy",
    ],
  },
  {
    id: 6,
    name: "Grilled Chicken Caesar Salad",
    cookTime: "5 mins",
    price: 12,
    favorite: true,
    origin: ["USA", "Italy"],
    stars: 3,
    imageUrl: CeasarSalImage,
    tags: ["Lunch", "Dinner", "Salad", "Chicken", "Caesar", "apetizers"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 3 },
  { name: "Pizza", count: 1 },
  { name: "Lunch", count: 4 },
  { name: "SlowFood", count: 3 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 2 },
  { name: "Salad", count: 1 },
];
